//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appWebCieluz.ServicioWebCieluz {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWebCieluz.ServidorProyectoSoap")]
    public interface ServidorProyectoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarClientes(appWebCieluz.ServicioWebCieluz.clCliente ObjCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarClientesAsync(appWebCieluz.ServicioWebCieluz.clCliente ObjCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarClientes(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarClientesAsync(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLoginEscritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdLoginEscritorio(string Correo, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLoginEscritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdLoginEscritorioAsync(string Correo, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLoginWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdLoginWeb(string Correo, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLoginWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdLoginWebAsync(string Correo, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarPedido(appWebCieluz.ServicioWebCieluz.clPedido objPed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarPedidoAsync(appWebCieluz.ServicioWebCieluz.clPedido objPed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarProducto(appWebCieluz.ServicioWebCieluz.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarProductoAsync(appWebCieluz.ServicioWebCieluz.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdEditarProducto(appWebCieluz.ServicioWebCieluz.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdEditarProductoAsync(appWebCieluz.ServicioWebCieluz.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEliminarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdEliminarProducto(appWebCieluz.ServicioWebCieluz.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdEliminarProductoAsync(appWebCieluz.ServicioWebCieluz.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarAdmin(appWebCieluz.ServicioWebCieluz.clAdministrador ObjAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarAdminAsync(appWebCieluz.ServicioWebCieluz.clAdministrador ObjAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarPro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarPro(appWebCieluz.ServicioWebCieluz.clProducto objProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarPro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProAsync(appWebCieluz.ServicioWebCieluz.clProducto objProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProEscritorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarProEscritorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProEscritorio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProEscritorioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProWeb2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarProWeb2(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProWeb2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProWeb2Async(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCli", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCli();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCli", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCliAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarPed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarPed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarPed", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarPedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdIndex(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdIndexAsync(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDTodosProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarDTodosProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDTodosProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDTodosProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDSencillasProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarDSencillasProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDSencillasProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDSencillasProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDAnimalesProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarDAnimalesProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDAnimalesProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDAnimalesProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDFloresProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarDFloresProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDFloresProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDFloresProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDPersonajesProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarDPersonajesProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDPersonajesProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDPersonajesProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDEspecialProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarDEspecialProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarDEspecialProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDEspecialProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCTodosProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCTodosProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCTodosProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCTodosProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCAmarilloProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCAmarilloProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCAmarilloProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCAmarilloProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCAzulProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCAzulProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCAzulProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCAzulProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCBlancoProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCBlancoProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCBlancoProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCBlancoProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCCafeProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCCafeProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCCafeProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCCafeProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCGrisProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCGrisProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCGrisProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCGrisProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCMoradoProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCMoradoProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCMoradoProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCMoradoProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCNaranjaProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCNaranjaProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCNaranjaProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCNaranjaProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCNegroProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCNegroProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCNegroProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCNegroProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCRojoProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCRojoProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCRojoProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCRojoProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCRosadoProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCRosadoProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCRosadoProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCRosadoProWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCVerdeProWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarCVerdeProWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarCVerdeProWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCVerdeProWebAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idClienteField;
        
        private string tipoDocumentoField;
        
        private string documentoField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string telefonoField;
        
        private string correoField;
        
        private string departamentoField;
        
        private string municipioField;
        
        private string direccionField;
        
        private string claveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("IdCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("TipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("Departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
                this.RaisePropertyChanged("Municipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clAdministrador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idAdministradorField;
        
        private string documentoField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string telefonoField;
        
        private string correoField;
        
        private string claveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdAdministrador {
            get {
                return this.idAdministradorField;
            }
            set {
                this.idAdministradorField = value;
                this.RaisePropertyChanged("IdAdministrador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProductoField;
        
        private string nombreField;
        
        private string codigoField;
        
        private string fotoField;
        
        private string precioField;
        
        private string colorField;
        
        private string diseñoField;
        
        private string descripcionField;
        
        private int idAdministradorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("IdProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("Foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("Precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Diseño {
            get {
                return this.diseñoField;
            }
            set {
                this.diseñoField = value;
                this.RaisePropertyChanged("Diseño");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int idAdministrador {
            get {
                return this.idAdministradorField;
            }
            set {
                this.idAdministradorField = value;
                this.RaisePropertyChanged("idAdministrador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clPedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idPedidoField;
        
        private int cantidadField;
        
        private int tallaField;
        
        private System.DateTime fechaField;
        
        private int precioTotalField;
        
        private string tipoPagoField;
        
        private int idProductoField;
        
        private int idClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
                this.RaisePropertyChanged("IdPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Talla {
            get {
                return this.tallaField;
            }
            set {
                this.tallaField = value;
                this.RaisePropertyChanged("Talla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PrecioTotal {
            get {
                return this.precioTotalField;
            }
            set {
                this.precioTotalField = value;
                this.RaisePropertyChanged("PrecioTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("TipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServidorProyectoSoapChannel : appWebCieluz.ServicioWebCieluz.ServidorProyectoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServidorProyectoSoapClient : System.ServiceModel.ClientBase<appWebCieluz.ServicioWebCieluz.ServidorProyectoSoap>, appWebCieluz.ServicioWebCieluz.ServidorProyectoSoap {
        
        public ServidorProyectoSoapClient() {
        }
        
        public ServidorProyectoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServidorProyectoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorProyectoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorProyectoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int mtdRegistrarClientes(appWebCieluz.ServicioWebCieluz.clCliente ObjCliente) {
            return base.Channel.mtdRegistrarClientes(ObjCliente);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarClientesAsync(appWebCieluz.ServicioWebCieluz.clCliente ObjCliente) {
            return base.Channel.mtdRegistrarClientesAsync(ObjCliente);
        }
        
        public System.Data.DataSet mtdListarClientes(int IdCliente) {
            return base.Channel.mtdListarClientes(IdCliente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarClientesAsync(int IdCliente) {
            return base.Channel.mtdListarClientesAsync(IdCliente);
        }
        
        public System.Data.DataSet mtdLoginEscritorio(string Correo, string Clave) {
            return base.Channel.mtdLoginEscritorio(Correo, Clave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdLoginEscritorioAsync(string Correo, string Clave) {
            return base.Channel.mtdLoginEscritorioAsync(Correo, Clave);
        }
        
        public System.Data.DataSet mtdLoginWeb(string Correo, string Clave) {
            return base.Channel.mtdLoginWeb(Correo, Clave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdLoginWebAsync(string Correo, string Clave) {
            return base.Channel.mtdLoginWebAsync(Correo, Clave);
        }
        
        public int mtdRegistrarPedido(appWebCieluz.ServicioWebCieluz.clPedido objPed) {
            return base.Channel.mtdRegistrarPedido(objPed);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarPedidoAsync(appWebCieluz.ServicioWebCieluz.clPedido objPed) {
            return base.Channel.mtdRegistrarPedidoAsync(objPed);
        }
        
        public int mtdRegistrarProducto(appWebCieluz.ServicioWebCieluz.clProducto objPro) {
            return base.Channel.mtdRegistrarProducto(objPro);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarProductoAsync(appWebCieluz.ServicioWebCieluz.clProducto objPro) {
            return base.Channel.mtdRegistrarProductoAsync(objPro);
        }
        
        public int mtdEditarProducto(appWebCieluz.ServicioWebCieluz.clProducto objPro) {
            return base.Channel.mtdEditarProducto(objPro);
        }
        
        public System.Threading.Tasks.Task<int> mtdEditarProductoAsync(appWebCieluz.ServicioWebCieluz.clProducto objPro) {
            return base.Channel.mtdEditarProductoAsync(objPro);
        }
        
        public int mtdEliminarProducto(appWebCieluz.ServicioWebCieluz.clProducto objPro) {
            return base.Channel.mtdEliminarProducto(objPro);
        }
        
        public System.Threading.Tasks.Task<int> mtdEliminarProductoAsync(appWebCieluz.ServicioWebCieluz.clProducto objPro) {
            return base.Channel.mtdEliminarProductoAsync(objPro);
        }
        
        public System.Data.DataSet mtdListarAdmin(appWebCieluz.ServicioWebCieluz.clAdministrador ObjAdmin) {
            return base.Channel.mtdListarAdmin(ObjAdmin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarAdminAsync(appWebCieluz.ServicioWebCieluz.clAdministrador ObjAdmin) {
            return base.Channel.mtdListarAdminAsync(ObjAdmin);
        }
        
        public System.Data.DataSet mtdListarPro(appWebCieluz.ServicioWebCieluz.clProducto objProducto) {
            return base.Channel.mtdListarPro(objProducto);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProAsync(appWebCieluz.ServicioWebCieluz.clProducto objProducto) {
            return base.Channel.mtdListarProAsync(objProducto);
        }
        
        public System.Data.DataSet mtdListarProEscritorio() {
            return base.Channel.mtdListarProEscritorio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProEscritorioAsync() {
            return base.Channel.mtdListarProEscritorioAsync();
        }
        
        public System.Data.DataSet mtdListarProWeb() {
            return base.Channel.mtdListarProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProWebAsync() {
            return base.Channel.mtdListarProWebAsync();
        }
        
        public System.Data.DataSet mtdListarProWeb2(int IdProducto) {
            return base.Channel.mtdListarProWeb2(IdProducto);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProWeb2Async(int IdProducto) {
            return base.Channel.mtdListarProWeb2Async(IdProducto);
        }
        
        public System.Data.DataSet mtdListarCli() {
            return base.Channel.mtdListarCli();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCliAsync() {
            return base.Channel.mtdListarCliAsync();
        }
        
        public System.Data.DataSet mtdListarPed() {
            return base.Channel.mtdListarPed();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarPedAsync() {
            return base.Channel.mtdListarPedAsync();
        }
        
        public System.Data.DataSet mtdIndex(int IdCliente) {
            return base.Channel.mtdIndex(IdCliente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdIndexAsync(int IdCliente) {
            return base.Channel.mtdIndexAsync(IdCliente);
        }
        
        public System.Data.DataSet mtdListarDTodosProWeb() {
            return base.Channel.mtdListarDTodosProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDTodosProWebAsync() {
            return base.Channel.mtdListarDTodosProWebAsync();
        }
        
        public System.Data.DataSet mtdListarDSencillasProWeb() {
            return base.Channel.mtdListarDSencillasProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDSencillasProWebAsync() {
            return base.Channel.mtdListarDSencillasProWebAsync();
        }
        
        public System.Data.DataSet mtdListarDAnimalesProWeb() {
            return base.Channel.mtdListarDAnimalesProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDAnimalesProWebAsync() {
            return base.Channel.mtdListarDAnimalesProWebAsync();
        }
        
        public System.Data.DataSet mtdListarDFloresProWeb() {
            return base.Channel.mtdListarDFloresProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDFloresProWebAsync() {
            return base.Channel.mtdListarDFloresProWebAsync();
        }
        
        public System.Data.DataSet mtdListarDPersonajesProWeb() {
            return base.Channel.mtdListarDPersonajesProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDPersonajesProWebAsync() {
            return base.Channel.mtdListarDPersonajesProWebAsync();
        }
        
        public System.Data.DataSet mtdListarDEspecialProWeb() {
            return base.Channel.mtdListarDEspecialProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarDEspecialProWebAsync() {
            return base.Channel.mtdListarDEspecialProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCTodosProWeb() {
            return base.Channel.mtdListarCTodosProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCTodosProWebAsync() {
            return base.Channel.mtdListarCTodosProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCAmarilloProWeb() {
            return base.Channel.mtdListarCAmarilloProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCAmarilloProWebAsync() {
            return base.Channel.mtdListarCAmarilloProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCAzulProWeb() {
            return base.Channel.mtdListarCAzulProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCAzulProWebAsync() {
            return base.Channel.mtdListarCAzulProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCBlancoProWeb() {
            return base.Channel.mtdListarCBlancoProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCBlancoProWebAsync() {
            return base.Channel.mtdListarCBlancoProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCCafeProWeb() {
            return base.Channel.mtdListarCCafeProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCCafeProWebAsync() {
            return base.Channel.mtdListarCCafeProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCGrisProWeb() {
            return base.Channel.mtdListarCGrisProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCGrisProWebAsync() {
            return base.Channel.mtdListarCGrisProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCMoradoProWeb() {
            return base.Channel.mtdListarCMoradoProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCMoradoProWebAsync() {
            return base.Channel.mtdListarCMoradoProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCNaranjaProWeb() {
            return base.Channel.mtdListarCNaranjaProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCNaranjaProWebAsync() {
            return base.Channel.mtdListarCNaranjaProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCNegroProWeb() {
            return base.Channel.mtdListarCNegroProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCNegroProWebAsync() {
            return base.Channel.mtdListarCNegroProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCRojoProWeb() {
            return base.Channel.mtdListarCRojoProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCRojoProWebAsync() {
            return base.Channel.mtdListarCRojoProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCRosadoProWeb() {
            return base.Channel.mtdListarCRosadoProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCRosadoProWebAsync() {
            return base.Channel.mtdListarCRosadoProWebAsync();
        }
        
        public System.Data.DataSet mtdListarCVerdeProWeb() {
            return base.Channel.mtdListarCVerdeProWeb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarCVerdeProWebAsync() {
            return base.Channel.mtdListarCVerdeProWebAsync();
        }
    }
}
